serverPort: 8080
debug: true
allowedHosts: ['127.0.0.1', '\[::1\]', '192.168.1.17']
zip: 29523
hubTimezone: 'UTC'
database:
  database: smartthings
  host: localhost
  port: 3306
  user: root
  password: ''
  socket: ''
  driver: 'mysql'
